name: .NET Continuous Integration

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Run tests
      env:
        SpaceTrackSdkOptions__Password: ${{ secrets.SPACE_TRACK_PASSWORD }}
        SpaceTrackSdkOptions__Username: ${{ secrets.SPACE_TRACK_USERNAME }}
        SpaceTrackSdkOptions__ApiUrl: "https://for-testing-only.space-track.org/"
        SpaceTrackSdkOptions__AuthEndpoint: "ajaxauth/login"
      run: dotnet test --logger GitHubActions ./src/SpaceTrackSdk.sln
